apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-y-d
  namespace: petclinic
  labels:
    app: app-y
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-y
  template:
    metadata:
      labels:
        app: app-y
    spec:
      containers:
      - image: amitmohleji/appy:{{BUILD_NUMBER}}
        name: app-y
---
apiVersion: v1
kind: Service
metadata:
  name: app-y
  namespace: petclinic
spec:
  selector: 
    app: app-y
  type: ClusterIP
  ports:
      - port: 8080
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: app-y
  namespace: petclinic
spec:
  to:
    kind: Service
    name: app-y
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None
status:
  ingress:
    - routerName: default
      conditions:
        - type: Admitted
          status: 'True'
      wildcardPolicy: None

